scan_filter_chain:
- name: wheelBox
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle: -3.1415
    upper_angle: -1.57
- name: wheelBox2
  type: LaserScanAngularBoundsFilter
  params:
    lower_angle:  1.57
    upper_angle:  3.1415
