DWAPlannerROS: {acc_lim_theta: 1.0, acc_lim_x: 0.6, acc_lim_y: 0.0, acc_limit_trans: 0.6,
  angular_sim_granularity: 0.1, forward_point_distance: 0.0, goal_distance_bias: 24.0,
  holonomic_robot: false, latch_xy_goal_tolerance: true, max_rot_vel: 0.4, max_scaling_factor: 0.2,
  max_trans_vel: 0.4, max_vel_x: 0.4, max_vel_y: 0.0, min_rot_vel: 0.0, min_trans_vel: 0.0,
  min_vel_x: 0.0, min_vel_y: 0.0, occdist_scale: 0.01, oscillation_reset_angle: 0.2,
  oscillation_reset_dist: 0.05, path_distance_bias: 32.0, prune_plan: true, restore_defaults: false,
  rot_stopped_vel: 0.01, scaling_speed: 0.25, sim_granularity: 0.025, sim_time: 2.1,
  stop_time_buffer: 0.2, trans_stopped_vel: 0.01, twirling_scale: 0.0, use_dwa: true,
  vth_samples: 20, vx_samples: 10, vy_samples: 1, xy_goal_tolerance: 0.5, yaw_goal_tolerance: 0.5}
NavfnROS: {allow_unknown: false, default_tolerance: 0.0}
aggressive_reset:
  layer_names: [obstacle_layer]
  reset_distance: 0.38
base_global_planner: strands_navfn/NavfnROS
base_local_planner: dwa_local_planner/DWAPlannerROS
clearing_rotation_allowed: true
conservative_reset:
  layer_names: [obstacle_layer]
  reset_distance: 2.0
conservative_reset_dist: 3.0
controller_frequency: 10.0
controller_patience: 15.0
global_costmap:
  footprint: '[[-0.211159,-0.295],[0.013709,-0.297036],[0.102681,-0.254027],[0.199937,-0.143212],[0.231037,-0.049411],[0.219249,0.097558],[0.140899,0.222458],[0.059921,0.279099],[-0.034768,0.307378],[-0.211159,0.295],[-0.511159,0.1],[-0.511159,-0.1],[-0.311159,-0.25]]'
  footprint_padding: 0.0001
  global_frame: /map
  global_inflation_layer: {cost_scaling_factor: 5.0, enabled: true, inflate_unknown: false,
    inflation_radius: 0.8}
  height: 10
  local_inflation_layer: {cost_scaling_factor: 5.0, inflation_radius: 0.2}
  map_layer: {enabled: true, map_topic: /map}
  map_type: voxel
  obstacle_layer:
    clear_sensor: {clearing: true, data_type: PointCloud2, marking: false, max_obstacle_height: 1.1,
      min_obstacle_height: -0.1, observation_persistence: 0.0, raytrace_range: 4.0,
      topic: /move_base/points_clearing}
    cliff_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.15,
      min_obstacle_height: 0.1, observation_persistence: 0.0, obstacle_range: 3.0,
      topic: /move_base/points_cliff}
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    head_clear_sensor: {clearing: true, data_type: PointCloud2, marking: false, max_obstacle_height: 1.1,
      min_obstacle_height: -0.2, observation_persistence: 0.0, raytrace_range: 5.0,
      topic: /move_base/head_points_clearing}
    head_cloud_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.9,
      min_obstacle_height: 0.3, observation_persistence: 0.0, obstacle_range: 3.0,
      topic: /move_base/head_points_obstacle}
    laser_clearing: {clearing: true, data_type: LaserScan, marking: false, sensor_frame: base_laser_link,
      topic: scan}
    laser_obstacle: {clearing: false, data_type: LaserScan, marking: true, sensor_frame: base_laser_link,
      topic: /move_base/scan_obstacle}
    mark_threshold: 0
    max_obstacle_height: 2.0
    observation_sources: laser_obstacle laser_clearing point_cloud_sensor clear_sensor
      cliff_sensor head_cloud_sensor head_clear_sensor
    obstacle_range: 2.5
    origin_z: 0.0
    point_cloud_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.9,
      min_obstacle_height: 0.1, observation_persistence: 0.0, obstacle_range: 2.0,
      topic: /move_base/points_obstacle}
    raytrace_range: 3.0
    track_unknown_space: true
    unknown_threshold: 6
    z_resolution: 0.2
    z_voxels: 6
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - {name: map_layer, type: 'costmap_2d::StaticLayer'}
  - {name: obstacle_layer, type: 'costmap_2d::VoxelLayer'}
  - {name: global_inflation_layer, type: 'costmap_2d::InflationLayer'}
  publish_frequency: 0.5
  resolution: 0.05
  robot_base_frame: /base_link
  robot_radius: 0.46
  rolling_window: false
  static_map: true
  transform_tolerance: 0.3
  update_frequency: 5.0
  width: 10
local_costmap:
  footprint: '[[-0.211159,-0.295],[0.013709,-0.297036],[0.102681,-0.254027],[0.199937,-0.143212],[0.231037,-0.049411],[0.219249,0.097558],[0.140899,0.222458],[0.059921,0.279099],[-0.034768,0.307378],[-0.211159,0.295],[-0.511159,0.1],[-0.511159,-0.1],[-0.311159,-0.25]]'
  footprint_padding: 0.0001
  global_frame: /map
  global_inflation_layer: {cost_scaling_factor: 5.0, inflation_radius: 0.8}
  height: 4
  local_inflation_layer: {cost_scaling_factor: 5.0, enabled: true, inflate_unknown: false,
    inflation_radius: 0.2}
  map_layer: {map_topic: /map}
  map_type: voxel
  obstacle_layer:
    clear_sensor: {clearing: true, data_type: PointCloud2, marking: false, max_obstacle_height: 1.1,
      min_obstacle_height: -0.1, observation_persistence: 0.0, raytrace_range: 4.0,
      topic: /move_base/points_clearing}
    cliff_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.15,
      min_obstacle_height: 0.1, observation_persistence: 0.0, obstacle_range: 3.0,
      topic: /move_base/points_cliff}
    combination_method: 1
    enabled: true
    footprint_clearing_enabled: true
    head_clear_sensor: {clearing: true, data_type: PointCloud2, marking: false, max_obstacle_height: 1.1,
      min_obstacle_height: -0.2, observation_persistence: 0.0, raytrace_range: 5.0,
      topic: /move_base/head_points_clearing}
    head_cloud_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.9,
      min_obstacle_height: 0.3, observation_persistence: 0.0, obstacle_range: 3.0,
      topic: /move_base/head_points_obstacle}
    laser_clearing: {clearing: true, data_type: LaserScan, marking: false, sensor_frame: base_laser_link,
      topic: scan}
    laser_obstacle: {clearing: false, data_type: LaserScan, marking: true, sensor_frame: base_laser_link,
      topic: /move_base/scan_obstacle}
    mark_threshold: 0
    max_obstacle_height: 2.0
    observation_sources: laser_obstacle laser_clearing point_cloud_sensor clear_sensor
      cliff_sensor head_cloud_sensor head_clear_sensor
    obstacle_range: 2.5
    origin_z: 0.0
    point_cloud_sensor: {clearing: false, data_type: PointCloud2, marking: true, max_obstacle_height: 0.9,
      min_obstacle_height: 0.1, observation_persistence: 0.0, obstacle_range: 2.0,
      topic: /move_base/points_obstacle}
    publish_voxel_map: true
    raytrace_range: 3.0
    track_unknown_space: true
    unknown_threshold: 6
    z_resolution: 0.2
    z_voxels: 6
  origin_x: 0.0
  origin_y: 0.0
  plugins:
  - {name: obstacle_layer, type: 'costmap_2d::VoxelLayer'}
  - {name: local_inflation_layer, type: 'costmap_2d::InflationLayer'}
  publish_frequency: 2.0
  resolution: 0.05
  robot_base_frame: /base_link
  robot_radius: 0.46
  rolling_window: true
  static_map: false
  transform_tolerance: 0.3
  update_frequency: 5.0
  width: 4
max_planning_retries: -1
oscillation_distance: 0.5
oscillation_timeout: 0.0
planner_frequency: 0.5
planner_patience: 5.0
recovery_behavior_enabled: true
recovery_behaviors:
- {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
- {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery}
restore_defaults: false
shutdown_costmaps: false